### GENERAL ###
namespace: test-app
replicaCount: 1
healthcheck: false

volumes:
  - name: app
    hostPath:
      # For windows you will need prefix of /run/desktop/mnt/host/
      path: /run/desktop/mnt/host/c/users/kozmi/Documents/github/lsapp
      # For linux and mac
      # path: /home/kozmi/documents/github/lsapp

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: test.dev
      paths:
        - /
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

### APPLICATIONS ###
app:
  image:
    repository: bencejob/laravel-php74
    pullPolicy: IfNotPresent
    tag: "latest"
  volumeMounts:
    - name: app
      mountPath: /var/www/html
  healthcheck:
    enabled: true
    period: 5

nginx:
  image:
    repository: bencejob/laravel-nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  volumeMounts: 
    - name: app
      mountPath: /var/www/html
  healthcheck:
    enabled: true
    period: 5

scheduler:
  enabled: false
  command:
    - php
    - artisan
    - queue:work
  volumeMounts:
    - name: app
      mountPath: /var/www/html
  healthcheck:
    enabled: true
    period: 5
