apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}
  namespace: {{ include "laravel.name" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      laravel.com/pod-type: web
  template:
    metadata:
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
        laravel.com/pod-type: web
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: php-fpm
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          volumeMounts:
            {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          {{- if .Values.app.healthcheck.enabled }}
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          {{- end }}
        {{- if .Values.scheduler.enabled }}
        - name: scheduler
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            {{- toYaml .Values.scheduler.command | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.scheduler.volumeMounts | nindent 12 }}
          {{- if .Values.scheduler.healthcheck.enabled }}
          readinessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          livenessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          {{- end }}
        {{- end }}
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            {{- toYaml .Values.nginx.volumeMounts | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.nginx.healthcheck.enabled }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - service nginx status | grep running
            initialDelaySeconds: {{ .Values.nginx.healthcheck.period }}
            periodSeconds: {{ .Values.nginx.healthcheck.period }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - service nginx status | grep running
            initialDelaySeconds: {{ .Values.nginx.healthcheck.period }}
            periodSeconds: {{ .Values.nginx.healthcheck.period }}
          {{- end }}
