{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "laravel.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  secretName: {{ .Values.namespace }}-tls
  issuerRef:
    name: selfsigned
{{- end }}
